language: haskell

ghc:
  - 7.6.3
  - 7.4.2

before_install:
    # Fetch the latest feldspar-language and feldspar-compiler from github
    - git clone -v -b master https://github.com/Feldspar/feldspar-language
    - (cd feldspar-language && git rev-parse HEAD)
    - git clone -v -b master https://github.com/Feldspar/feldspar-compiler
    - (cd feldspar-compiler && git rev-parse HEAD)

    # Try installing some of the build-deps with apt-get for speed
    # - ./tools/travis-cabal-apt-install $mode feldspar-language/ feldspar-compiler/ ./
    - cabal install tasty feldspar-language/ feldspar-compiler/
